apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-template
data:
  default.conf: |
    server {
        listen 80;
        location / {
            return 200 "Hello from NGINX!\n";
        }
        location /env {
            default_type text/plain;
            return 200 "APP_ENV=$APP_ENV\nWELCOME_MSG=$WELCOME_MSG\nDB_USER=$DB_USER\n";
        }
    }

