  {{- if (.Values.istio.enabled | default false) }}
  {{- $vs := (.Values.istio.virtualService | default dict) }}
  {{- $hosts := ($vs.hosts | default list) }}
  {{- $gateways := ($vs.gateways | default list) }}
  {{- $http := ($vs.http | default dict) }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- if $hosts }}
  {{ toYaml $hosts | nindent 4 }}
  {{- else }}
- "*"
  {{- end }}
gateways:
  {{- if $gateways }}
  {{ toYaml $gateways | nindent 4 }}
  {{- else }}
- "mesh"
  {{- end }}
http:
  - match:
      - uri:
          prefix: {{ ($http.prefix | default "/") | quote }}
    route:
      - destination:
          host: {{ include "mlflow.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: {{ .Values.service.port }}
  {{- end }}